name: Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install doc dependencies
        run: pip install .[dev]
      - name: Build & Deploy
        run: mkdocs gh-deploy --force --strict